/**
 * KRISLYNX visualization system.
 *
 * Every visualization server-renders its complete content (labels, panels, legends) as HTML, so it reads
 * without JavaScript, without motion and to screen readers. src/client/viz.ts adds selection (click, hover on
 * fine pointers, focus, arrow keys), path lighting (root[data-active]) and one-time autoplay. All motion is
 * CSS (no Lottie runtime is available offline; see docs/VISUAL-TRANSFORMATION.md → Animation inventory) and
 * stops under prefers-reduced-motion. CSP forbids inline styles, so geometry-dependent CSS is generated by
 * vizCss() from the same constants that draw the SVG.
 *
 * Content rules: technologies derive from config/technology.ts; products and statuses from config/products.ts;
 * EduLynx modules from config/products.ts; anything illustrative is labelled and contains no numbers.
 */
import type { SafeHtml } from "@kx/jsx-runtime";
import { techLayers } from "../config/technology";
import { lifecycle } from "../config/lifecycle";
import { edulynx, products, statusLabel } from "../config/products";
import { serviceFlows, services } from "../config/services";
import { systemFlow, systemNodes } from "../config/system";
import { caseStudies } from "../config/work";
import { StatusBadge, TechLabel } from "./ui";
import { Picture } from "./media";

const pad = (n: number): string => String(n).padStart(2, "0");

function Fig(props: { n?: string; title: string }): SafeHtml {
  return (
    <p class="fig-label" aria-hidden="true">
      <span>{props.n ? `FIG. ${props.n}` : "SYSTEM"}</span>
      <span>{props.title}</span>
    </p>
  );
}

/** Technologies for a system node, derived from the approved sources (never typed by hand). */
export function techFor(keys: readonly string[]): string[] {
  return keys.flatMap((k) => techLayers.find((l) => l.key === k)?.items ?? []);
}

/* ========================================================== SYSTEM MAP */

const W = 600;
const H = 440;
const C = { x: 300, y: 220 };
export const sysPos = systemNodes.map((n, i) => {
  const a = ((-90 + 60 * i) * Math.PI) / 180;
  return { key: n.key, x: Math.round(C.x + 215 * Math.cos(a)), y: Math.round(C.y + 158 * Math.sin(a)) };
});
const curve = (x: number, y: number): string => {
  const mx = (C.x + x) / 2 + (y - C.y) * 0.18;
  const my = (C.y + y) / 2 - (x - C.x) * 0.18;
  return `M${C.x} ${C.y} Q${Math.round(mx)} ${Math.round(my)} ${x} ${y}`;
};

function SystemLines(): SafeHtml {
  return (
    <svg class="smap__svg" viewBox={`0 0 ${W} ${H}`} aria-hidden="true" focusable="false">
      <ellipse class="smap__orbit" cx={String(C.x)} cy={String(C.y)} rx="215" ry="158" />
      <ellipse class="smap__orbit smap__orbit--inner" cx={String(C.x)} cy={String(C.y)} rx="120" ry="88" />
      {sysPos.map((p, i) => {
        const n = systemNodes[i];
        return (
          <g class={`smap__link smap__link--${p.key} tone--${n?.tone ?? "blue"}`}>
            <path class="smap__path" d={curve(p.x, p.y)} />
            <path class={`smap__comet smap__comet--i${i}`} d={curve(p.x, p.y)} />
          </g>
        );
      })}
    </svg>
  );
}

/**
 * variant "hero": ambient assembly + links into the system section.
 * variant "full": explorer with panels (What it is / What KrisLynx does / Related technology).
 */
export function SystemMap(props: { variant: "hero" | "full" }): SafeHtml {
  const hero = props.variant === "hero";
  const core = (
    <div class="smap__core" aria-hidden="true">
      <span class="mono">SYSTEM CORE</span>
      <strong>KrisLynx</strong>
    </div>
  );
  if (hero) {
    return (
      <figure class="smap smap--hero" data-map="" aria-labelledby="smap-hero-cap">
        <div class="smap__stage" data-parallax="">
          <SystemLines />
          {core}
          {systemNodes.map((n, i) => (
            <a href={`#sys-tab-${n.key}`} class={`smap__node smap__node--${n.key} smap__node--i${i} tone--${n.tone}`} data-node={n.key} data-select={`sys-tab-${n.key}`}>
              <span class="smap__dot" aria-hidden="true"></span>
              {n.label}
            </a>
          ))}
        </div>
        <ol class="smap__flow" aria-label="How work moves through a system">
          {systemFlow.map((s, i) => (
            <li class={`smap__flow-step smap__flow-step--i${i}`}>
              <span class="mono" aria-hidden="true">
                {pad(i + 1)}
              </span>
              {s}
            </li>
          ))}
        </ol>
        <figcaption id="smap-hero-cap" class="visually-hidden">
          The KrisLynx system: products, software, AI, data, cloud and operations connected to one engineering core. Work moves from input through processing and intelligence to a working system and a real outcome.
        </figcaption>
      </figure>
    );
  }
  return (
    <div class="smap smap--full viz" data-viz="system" data-active={systemNodes[0]?.key}>
      <Fig n="01" title="The KrisLynx system — select a node" />
      <div class="smap__grid">
        <div class="smap__stage" role="tablist" aria-label="System components">
          <SystemLines />
          {core}
          {systemNodes.map((n, i) => (
            <button
              type="button"
              role="tab"
              class={`smap__node smap__node--${n.key} smap__node--i${i} tone--${n.tone}`}
              id={`sys-tab-${n.key}`}
              data-key={n.key}
              aria-controls={`sys-panel-${n.key}`}
              aria-selected={i === 0 ? "true" : "false"}
              tabindex={i === 0 ? "0" : "-1"}
            >
              <span class="smap__dot" aria-hidden="true"></span>
              {n.label}
            </button>
          ))}
        </div>
        <div class="smap__panels">
          {systemNodes.map((n, i) => {
            const tech = n.products ? products.map((p) => `${p.name} — ${statusLabel[p.status]}`) : techFor(n.tech);
            return (
              <section class={`smap__panel glass viz-panel tone--${n.tone}`} id={`sys-panel-${n.key}`} role="tabpanel" aria-labelledby={`sys-tab-${n.key}`} data-viz-panel={n.key} data-inactive={i === 0 ? undefined : ""}>
                <TechLabel index={pad(i + 1)} label={n.label} />
                <dl class="smap__facts">
                  <div>
                    <dt>What it is</dt>
                    <dd>{n.what}</dd>
                  </div>
                  <div>
                    <dt>What KrisLynx does</dt>
                    <dd>{n.does}</dd>
                  </div>
                  <div>
                    <dt>{n.products ? "Products" : "Related technology"}</dt>
                    <dd>
                      <ul class="chips">
                        {tech.map((t) => (
                          <li>{t}</li>
                        ))}
                      </ul>
                    </dd>
                  </div>
                </dl>
              </section>
            );
          })}
        </div>
      </div>
    </div>
  );
}

/* ======================================================= LIFECYCLE (8) */

export function LifecycleFlow(): SafeHtml {
  return (
    <div class="lf viz" data-viz="lifecycle" data-active={lifecycle[0].key}>
      <Fig n="03" title="Idea → production — select a stage" />
      <div class="lf__track" role="tablist" aria-label="Engineering stages">
        {lifecycle.map((s, i) => (
          <button
            type="button"
            role="tab"
            class={`lf__stage lf__stage--i${i}`}
            id={`lf-tab-${s.key}`}
            data-key={s.key}
            aria-controls={`lf-panel-${s.key}`}
            aria-selected={i === 0 ? "true" : "false"}
            tabindex={i === 0 ? "0" : "-1"}
          >
            <span class="lf__dot mono" aria-hidden="true">
              {pad(i + 1)}
            </span>
            <span class="lf__name">{s.name}</span>
          </button>
        ))}
      </div>
      <div class="lf__panels">
        {lifecycle.map((s, i) => (
          <section class="lf__panel glass viz-panel" id={`lf-panel-${s.key}`} role="tabpanel" aria-labelledby={`lf-tab-${s.key}`} data-viz-panel={s.key} data-inactive={i === 0 ? undefined : ""}>
            <div>
              <TechLabel index={`${pad(i + 1)}/${pad(lifecycle.length)}`} label={s.name} />
              <h3 class="display-3">{s.body}</h3>
              <p class="lf__does">{s.body}</p>
            </div>
            <dl class="lf__facts">
              <div>
                <dt>Tools & technology</dt>
                <dd>
                  <ul class="chips">
<li>{s.output}</li>
                  </ul>
                </dd>
              </div>
              <div>
                <dt>Output</dt>
                <dd class="lf__output">{s.output}</dd>
              </div>
            </dl>
          </section>
        ))}
      </div>
    </div>
  );
}

/* ============================================================ DATA FLOW */

const dfStages = [
  { key: "input", name: "Input", text: "People and systems produce events: a form submitted, attendance marked, a file uploaded." },
  { key: "data", name: "Data", text: "Events become records in one shared model, so every part of the system reads the same truth." },
  { key: "processing", name: "Processing", text: "Business rules validate, calculate and route: fees due, permissions checked, reports assembled." },
  { key: "intelligence", name: "Intelligence", text: "Where it earns its place, AI summarises and flags patterns across records — with reasons attached." },
  { key: "decision", name: "Decision", text: "A person with the right role reviews and decides. The system records who decided what." },
  { key: "action", name: "Action", text: "The outcome goes back into operations: a reminder sent, a report filed, a workflow moved on." },
];
/** Signal lanes: type, label, start stage index, end stage index. */
const dfLanes = [
  { key: "app", label: "Application data", tone: "blue", from: 0, to: 2 },
  { key: "sys", label: "System data", tone: "cyan", from: 1, to: 4 },
  { key: "intel", label: "Intelligence", tone: "violet", from: 2, to: 4 },
  { key: "out", label: "Output", tone: "mint", from: 4, to: 5 },
] as const;

export function DataFlow(): SafeHtml {
  const colX = (i: number): number => 50 + i * 100;
  return (
    <div class="df viz" data-viz="dataflow" data-active="input">
      <Fig n="04" title="Data flow — select a stage" />
      <div class="df__stage">
        <svg class="df__svg" viewBox="0 0 600 150" aria-hidden="true" focusable="false">
          {dfStages.map((_, i) => (
            <line class={`df__col df__col--i${i}`} x1={String(colX(i))} y1="8" x2={String(colX(i))} y2="142" />
          ))}
          {dfLanes.map((l, i) => {
            const y = 30 + i * 30;
            const d = `M${colX(l.from)} ${y} H${colX(l.to)}`;
            return (
              <g class={`df__lane tone--${l.tone}`}>
                <path class="df__path" d={d} />
                <path class={`df__comet df__comet--i${i}`} d={d} />
                <circle class="df__node" cx={String(colX(l.from))} cy={String(y)} r="3.5" />
                <circle class="df__node" cx={String(colX(l.to))} cy={String(y)} r="3.5" />
              </g>
            );
          })}
        </svg>
        <div class="df__tabs" role="tablist" aria-label="Data flow stages">
          {dfStages.map((s, i) => (
            <button type="button" role="tab" class={`df__tab df__tab--i${i}`} id={`df-tab-${s.key}`} data-key={s.key} aria-controls={`df-panel-${s.key}`} aria-selected={i === 0 ? "true" : "false"} tabindex={i === 0 ? "0" : "-1"}>
              <span class="mono" aria-hidden="true">
                {pad(i + 1)}
              </span>
              {s.name}
            </button>
          ))}
        </div>
      </div>
      <div class="df__foot">
        <div class="df__panels">
          {dfStages.map((s, i) => (
            <p class="df__panel viz-panel" id={`df-panel-${s.key}`} role="tabpanel" aria-labelledby={`df-tab-${s.key}`} data-viz-panel={s.key} data-inactive={i === 0 ? undefined : ""}>
              <strong>{s.name}.</strong> {s.text}
            </p>
          ))}
        </div>
        <ul class="df__legend" aria-label="Signal types">
          {dfLanes.map((l) => (
            <li class={`tone--${l.tone}`}>
              <span class="df__swatch" aria-hidden="true"></span>
              {l.label}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

/** Approved technology, grouped by layer (derived from technology.ts). */
export function TechMatrix(): SafeHtml {
  return (
    <dl class="tmx">
      {techLayers.map((l) => (
        <div class="tmx__row">
          <dt>
            <span class="mono">{l.name}</span>
            <span class="tmx__purpose">{l.purpose}</span>
          </dt>
          <dd>
            <ul class="chips">
              {l.items.map((t) => (
                <li>{t}</li>
              ))}
            </ul>
          </dd>
        </div>
      ))}
    </dl>
  );
}

/* ========================================================== AI PIPELINE */

const aiSteps = [
  { key: "question", name: "Question", text: "A principal asks, in plain language: “Which students need attention this week?”" },
  { key: "context", name: "Context", text: "Intent and scope are resolved: at-risk students, this school, this week — and the user’s role decides what they may see." },
  { key: "data", name: "Authorized data", text: "Only records this user is permitted to read are fetched, live: attendance, recent assessments, fee status." },
  { key: "model", name: "Model", text: `A language model (${edulynx.ai.provider}) receives the question, the permitted records and the school’s own thresholds.` },
  { key: "validation", name: "Validation", text: "The answer is checked against the source records; every flag must carry the reason it was raised." },
  { key: "response", name: "Response", text: "A short list with a reason and a suggested next step for each student — no black-box scores." },
  { key: "decision", name: "Human decision", text: "Staff decide what to do. The assistant suggests; people act, and the audit log records it." },
]

export function AIFlow(): SafeHtml {
  return (
    <div class="aip viz" data-viz="ai" data-active={aiSteps[0]?.key} data-viz-autoplay="">
      <Fig n="02" title="AI pipeline — illustrative example" />
      <p class="aip__boundary" aria-hidden="true">
        <span class="aip__zone aip__zone--ai mono">AI system · steps 01–06</span>
        <span class="aip__zone aip__zone--human mono">AI stops here · people decide</span>
      </p>
      <ol class="aip__steps" role="tablist" aria-label="AI pipeline steps">
        {aiSteps.map((s, i) => (
          <li class="aip__item" role="presentation">
            <button type="button" role="tab" class={`aip__step aip__step--i${i}`} id={`ai-tab-${s.key}`} data-key={s.key} aria-controls={`ai-panel-${s.key}`} aria-selected={i === 0 ? "true" : "false"} tabindex={i === 0 ? "0" : "-1"}>
              <span class="mono" aria-hidden="true">
                {pad(i + 1)}
              </span>
              {s.name}
            </button>
          </li>
        ))}
      </ol>
      <div class="aip__panels">
        {aiSteps.map((s, i) => (
          <section class="aip__panel viz-panel" id={`ai-panel-${s.key}`} role="tabpanel" aria-labelledby={`ai-tab-${s.key}`} data-viz-panel={s.key} data-inactive={i === 0 ? undefined : ""}>
            <p class="aip__text">{s.text}</p>
          </section>
        ))}
      </div>
      <p class="viz-note">Illustrative example based on the EduLynx AI operations assistant’s published capabilities. No real school data is shown.</p>
    </div>
  );
}

/* ===================================================== PRODUCT ECOSYSTEM */



/* ================================================= EDULYNX ENVIRONMENT */

const opsKeys = ["students", "attendance", "academics", "exams", "finance", "communication", "timetable", "reports", "staff", "admin", "ai"] as const;
/** Split an approved module description into its feature phrases (used as illustrative widget titles). */
export const featuresOf = (body: string): string[] =>
  body
    .replace(/\.$/, "")
    .split(/,\s*/)
    .map((s) => s.trim().replace(/^and\s+/, ""))
    .filter((s) => s.length > 2)
    .slice(0, 6)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1));

export function EduLynxMap(): SafeHtml {
  const mods = opsKeys.map((k) => edulynx.modules.find((m) => m.key === k)).filter((m) => m !== undefined);
  const sec = edulynx.modules.find((m) => m.key === "security");
  return (
    <div class="edx viz lightfield lightfield--cyan" data-viz="edulynx" data-active="students">
      <Fig n="01" title="EduLynx ERP — select a module" />
      <div class="edx__grid">
        <aside class="edx__inst" aria-label="Institution structure">
          <p class="tlabel">
            <span>Institution</span>
          </p>
          <p class="edx__inst-name">One school · one isolated tenant</p>
          <ul class="edx__roles">
            {edulynx.architecture.roles.map((r) => (
              <li>
                <span class="edx__role-dot" aria-hidden="true"></span>
                {r}
              </li>
            ))}
          </ul>
          <p class="edx__inst-note">Each role sees only what it is authorised to see.</p>
        </aside>
        <div class="edx__app glass glass--strong">
          <div class="edx__bar" aria-hidden="true">
            <span></span>
            <span></span>
            <span></span>
            <em class="mono">{edulynx.screenshots.length ? "EduLynx ERP" : "EduLynx ERP · illustrative interface"}</em>
          </div>
          <div class="edx__body">
            <div class="edx__nav" role="tablist" aria-label="EduLynx ERP modules" aria-orientation="vertical">
              {mods.map((m, i) => (
                <button
                  type="button"
                  role="tab"
                  class={`edx__tab${m.key === "ai" ? " edx__tab--ai" : ""}`}
                  id={`em-tab-${m.key}`}
                  data-key={m.key}
                  aria-controls={`em-panel-${m.key}`}
                  aria-selected={i === 0 ? "true" : "false"}
                  tabindex={i === 0 ? "0" : "-1"}
                >
                  {m.name}
                </button>
              ))}
            </div>
            <div class="edx__screens">
              {mods.map((m, i) => (
                <section class={`edx__screen viz-panel${m.key === "ai" ? " edx__screen--ai" : ""}`} id={`em-panel-${m.key}`} role="tabpanel" aria-labelledby={`em-tab-${m.key}`} data-viz-panel={m.key} data-inactive={i === 0 ? undefined : ""}>
                  <div class="edx__screen-head">
                    <h3>{m.name}</h3>
                    <span class="mono">{m.key === "ai" ? "AI LAYER · reads all modules" : "MODULE · writes the institution record"}</span>
                  </div>
                  {(() => {
                    // Real screenshot slot: shown only when the owner supplies one for this module.
                    const shot = edulynx.screenshots.find((x) => "module" in x && (x as Record<string, string>).module === m.key);
                    return shot ? (
                      <figure class="edx__shot">
                        <Picture name={shot.image} alt={shot.caption} sizes="(min-width: 64rem) 60vw, 100vw" />
                        <figcaption class="edx__shot-tag mono">Product screenshot · {shot.caption}</figcaption>
                      </figure>
                    ) : (
                      <>
                        <p class="edx__shot-tag edx__shot-tag--illus mono">Illustrative</p>
                        <ul class="edx__widgets" aria-label={`${m.name} capabilities`}>
                          {featuresOf(m.body).map((f) => (
                            <li class="edx__widget">
                              <span class="edx__row-t">{f}</span>
                              <span class="edx__row-go" aria-hidden="true">
                                ›
                              </span>
                            </li>
                          ))}
                        </ul>
                      </>
                    );
                  })()}
                </section>
              ))}
            </div>
          </div>
        </div>
      </div>
      <div class="edx__flow" aria-label="How module data moves">
        <span class="edx__flow-step edx__flow-step--mod">Selected module</span>
        <span class="edx__flow-arrow" aria-hidden="true"></span>
        <span class="edx__flow-step">One institution record</span>
        <span class="edx__flow-arrow" aria-hidden="true"></span>
        <span class="edx__flow-step">Reports & analytics</span>
        <span class="edx__flow-arrow" aria-hidden="true"></span>
        <span class="edx__flow-step edx__flow-step--ai">AI operations assistant</span>
      </div>
      {sec ? (
        <p class="edx__foundation">
          <span class="mono">FOUNDATION</span> <b>{sec.name}.</b> {sec.body}
        </p>
      ) : null}
      <div class="edx__bridge">
        <p class="tlabel"><span class="tlabel__index">From product to engineering</span></p>
        <p class="edx__bridge-text">From product requirements to working software — the same engineering process we use for every system we build.</p>
        <a href="/services" class="btn--arrow">How we build it <span class="arrow" aria-hidden="true">→</span></a>
      </div>
    </div>
  );
}

/* ====================================================== SERVICE FLOW */

export function ServiceFlow(props: { slug: string; compact?: boolean }): SafeHtml {
  const f = serviceFlows[props.slug];
  if (!f) return <></>;
  return (
    <figure class={`svf${props.compact ? " svf--compact" : ""}`} aria-label={`${f.title}: ${f.steps.join(", then ")}`}>
      {props.compact ? null : <Fig title={`${f.title} · conceptual flow`} />}
      <ol class="svf__steps" aria-hidden="true">
        {f.steps.map((s, i) => (
          <li class={`svf__step svf__step--i${i}`}>
            <span class="mono">{pad(i + 1)}</span>
            {s}
          </li>
        ))}
      </ol>
    </figure>
  );
}

/** "Choose the system you need us to build." */
export function ServiceChooser(): SafeHtml {
  return (
    <div class="svc viz" data-viz="services" data-active={services[0]?.slug}>
      <div class="svc__list" role="tablist" aria-label="Systems we build" aria-orientation="vertical">
        {services.map((s, i) => (
          <button type="button" role="tab" class="svc__tab" id={`svc-tab-${s.slug}`} data-key={s.slug} aria-controls={`svc-panel-${s.slug}`} aria-selected={i === 0 ? "true" : "false"} tabindex={i === 0 ? "0" : "-1"}>
            <span class="mono" aria-hidden="true">
              {pad(i + 1)}
            </span>
            {s.name}
          </button>
        ))}
      </div>
      <div class="svc__panels">
        {services.map((s, i) => (
          <section class="svc__panel glass viz-panel" id={`svc-panel-${s.slug}`} role="tabpanel" aria-labelledby={`svc-tab-${s.slug}`} data-viz-panel={s.slug} data-inactive={i === 0 ? undefined : ""}>
            <h3 class="display-3">{s.name}</h3>
            <p class="svc__short">{s.short}</p>
            <ServiceFlow slug={s.slug} compact />
            <ul class="svc__caps">
              {s.capabilities.slice(0, 4).map((c) => (
                <li>{c.title}</li>
              ))}
            </ul>
            <a class="text-link" href={`/services/${s.slug}`}>
              How we build {s.name.toLowerCase()} →
            </a>
          </section>
        ))}
      </div>
    </div>
  );
}

/* ============================================================ CASE FILES */

export function CaseFiles(props: { compact?: boolean }): SafeHtml {
  return (
    <ol class={`cf${props.compact ? " cf--compact" : ""}`}>
      {caseStudies.map((c, i) => (
        <li class="cf__file glass glass-card">
          <a href={`/work/${c.slug}`} class="cf__link">
            <span class="cf__head">
              <span class="mono">PROJECT {pad(i + 1)}</span>
              <StatusBadge status={c.status} />
            </span>
            <span class="cf__name">{c.name}</span>
            <span class="cf__grid">
              <span class="cf__k mono">The problem</span>
              <span class="cf__v">{c.challenge.split(". ")[0]}.</span>
              <span class="cf__k mono">The system</span>
              <span class="cf__v">{c.summary}</span>
              <span class="cf__k mono">The engineering</span>
              <span class="cf__v">{c.approach[0]}</span>
              {c.status === "live" ? <span class="cf__k mono">The result</span> : null}
              {c.status === "live" ? <span class="cf__v">{c.statusDetail}</span> : null}
              <span class="cf__k mono">Technology</span>
              <span class="cf__v">{c.technology.slice(0, 3).join(" · ")}</span>
            </span>
            <span class="cf__open mono" aria-hidden="true">
              Open file →
            </span>
          </a>
        </li>
      ))}
    </ol>
  );
}

/* ============================================================ CTA PIPELINE */

export function ProjectPipeline(): SafeHtml {
  const steps = ["Your brief", "A short call", "A clear proposal", "First release"];
  return (
    <ol class="pp" aria-label="How a project starts">
      {steps.map((s, i) => (
        <li class={`pp__step pp__step--i${i}`}>
          <span class="mono">{pad(i + 1)}</span>
          {s}
        </li>
      ))}
    </ol>
  );
}

/* ============================================================ SECTION RAIL */

/** Desktop-only index of homepage sections ("how deep into the system you are"). */
export function SectionRail(props: { items: { id: string; n: string; label: string }[] }): SafeHtml {
  return (
    <nav class="rail" aria-label="Page sections" data-rail="">
      <ol>
        {props.items.map((it) => (
          <li>
            <a href={`#${it.id}`} data-rail-link={it.id}>
              <span class="mono">{it.n}</span>
              <span class="rail__label">{it.label}</span>
            </a>
          </li>
        ))}
      </ol>
    </nav>
  );
}

/* ================================================= generated geometry CSS */

export function vizCss(): string {
  const r: string[] = [];
  for (const p of sysPos) r.push(`.smap__node--${p.key}{left:${((p.x / W) * 100).toFixed(2)}%;top:${((p.y / H) * 100).toFixed(2)}%}`);
  for (const n of systemNodes) r.push(`.smap[data-active="${n.key}"] .smap__link--${n.key} .smap__path{stroke:var(--tone);stroke-opacity:.95;stroke-width:2}.smap[data-active="${n.key}"] .smap__node--${n.key}{border-color:var(--tone);color:var(--text-hi)}`);
  const lit = (root: string, item: string, keys: readonly string[]): void => {
    keys.forEach((k, i) => r.push(keys.slice(0, i + 1).map((_, j) => `.${root}[data-active="${k}"] .${item}--i${j}`).join(",") + "{--lit:1}"));
  };
  lit("lf", "lf__stage", lifecycle.map((s) => s.key));
  lit("aip", "aip__step", aiSteps.map((s) => s.key));
  dfStages.forEach((s, i) => {
    r.push(`.df[data-active="${s.key}"] .df__tab--i${i}{--lit:1}`);
    r.push(`.df[data-active="${s.key}"] .df__col--i${i}{stroke-opacity:.8}`);
  });
  for (const k of opsKeys) r.push(`.edx[data-active="${k}"] .edx__flow-step--mod::after{content:" · ${edulynx.modules.find((m) => m.key === k)?.name ?? ""}"}`);
  r.push(`.edx[data-active="ai"] .edx__flow-step--ai{border-color:var(--violet);color:var(--text-hi);box-shadow:0 0 0 4px rgba(185,168,255,.12)}`);
  return r.join("\n") + "\n";
}

/* ================================================= INFRASTRUCTURE PHOTOGRAPH (shared) */

/** The real network/server room (owner-confirmed; AI-enhanced, disclosed). Editorial labels only — no specs or telemetry. */
export function InfraPhoto(): SafeHtml {
  return (
    <figure class="infra" data-reveal="media">
      <div class="infra__frame">
        <Picture name="krislynx-infrastructure-server-room" mobile="krislynx-infrastructure-server-room-mobile" mobileSizes="100vw" alt="The KrisLynx office network and server room: workstation towers, a firewall, network switch and patch panel in an open rack, a UPS, a NAS and a locked cabinet, lit in blue" sizes="(min-width: 80rem) 78rem, 100vw" />
        <div class="infra__labels" aria-hidden="true">
          <span class="infra__label infra__label--a">
            <b>Infrastructure</b> / 01
          </span>
          <span class="infra__label infra__label--b">
            <b>Network</b>
          </span>
          <span class="infra__label infra__label--c">
            <b>Local environment</b> · Nandyal
          </span>
        </div>
      </div>
      <figcaption class="infra__cap">
        <strong>Behind every product is a system.</strong> The network and server room in our Nandyal office — where the architecture above becomes real. <span class="infra__note">Image enhanced for clarity.</span>
      </figcaption>
    </figure>
  );
}

/* ====================================================== PRODUCT SYSTEM (27 Sep 2026) */

/** EduLynx as the dominant flagship panel; every other product as a smaller module with its own mark. No status labels. */
export function ProductSystem(): SafeHtml {
  const flagship = products.find((p) => p.slug === "edulynx-erp");
  const others = products.filter((p) => p.slug !== "edulynx-erp");
  return (
    <div class="psys" data-reveal>
      {/* §9 constellation: subtle connecting lines (SVG behind the cards, decorative) */}
      <svg class="psys__lines" viewBox="0 0 1000 600" fill="none" aria-hidden="true" preserveAspectRatio="xMidYMid meet">
        <line x1="500" y1="80" x2="500" y2="280" stroke="currentColor" stroke-opacity="0.12" stroke-width="1" stroke-dasharray="4 6" />
        <line x1="500" y1="280" x2="200" y2="440" stroke="currentColor" stroke-opacity="0.08" stroke-width="1" stroke-dasharray="4 6" />
        <line x1="500" y1="280" x2="400" y2="440" stroke="currentColor" stroke-opacity="0.08" stroke-width="1" stroke-dasharray="4 6" />
        <line x1="500" y1="280" x2="600" y2="440" stroke="currentColor" stroke-opacity="0.08" stroke-width="1" stroke-dasharray="4 6" />
        <line x1="500" y1="280" x2="800" y2="440" stroke="currentColor" stroke-opacity="0.08" stroke-width="1" stroke-dasharray="4 6" />
        <circle cx="500" cy="80" r="3" fill="currentColor" opacity="0.2" />
        <text x="500" y="68" text-anchor="middle" font-family="var(--font-mono)" font-size="10" letter-spacing="0.14em" fill="currentColor" opacity="0.3">KRISLYNX</text>
      </svg>
      {flagship ? (
        <a href={flagship.href} class="psys__flag" data-event="product_click" data-event-label="edulynx-erp">
          <span class="psys__flag-kicker mono">Flagship · Education operations</span>
          <span class="psys__flag-name">{flagship.name}</span>
          <span class="psys__flag-sum">{flagship.summary}</span>
          <span class="psys__flag-facts">
            <span>{edulynx.modules.length} modules</span>
            <span>{edulynx.architecture.roles.length} roles</span>
            <span>AI assistant · {edulynx.ai.provider}</span>
          </span>
          <span class="psys__flag-cta">Explore EduLynx ERP →</span>
        </a>
      ) : null}
      <ul class="psys__grid">
        {others.map((p) => (
          <li class={`psys__mod psys__mod--${p.slug}`}>
            {p.mark ? (
              <span class="psys__mark">
                <Picture name={p.mark.image} alt={p.mark.alt} sizes="96px" />
              </span>
            ) : null}
            <span class="psys__cat mono">{p.category}</span>
            <span class="psys__name">{p.name}</span>
            <span class="psys__sum">{p.summary}</span>
            {p.href !== "/products" ? (
              <a class="psys__more" href={p.href}>
                Explore {p.name} <span aria-hidden="true">→</span>
              </a>
            ) : null}
          </li>
        ))}
      </ul>
    </div>
  );
}

/* ============================================================ v3.1: HERO CORE */

const hcNodes = [
  { key: "ai", label: "AI", x: 50, y: 9, tone: "violet", href: "#intelligence", note: "Assistants that answer only from data the user may see." },
  { key: "data", label: "Data", x: 11, y: 44, tone: "cyan", href: "#technology", note: "One record per organization — every module reads the same truth." },
  { key: "products", label: "Products", x: 89, y: 44, tone: "mint", href: "#flagship", note: "Software we run ourselves. EduLynx ERP is live." },
  { key: "apps", label: "Applications", x: 50, y: 67, tone: "blue", href: "#engineer", note: "The interfaces staff, schools and customers use every day." },
  { key: "people", label: "People", x: 50, y: 90, tone: "peach", href: "#about", note: "Everything ends with a person who can act on it." },
] as const;
const HC = { x: 50, y: 44 };

/** The KrisLynx core. Hover or focus a node: its path (and the paths it depends on) light; a note explains it. */
export function HeroCore(): SafeHtml {
  const seg = (x1: number, y1: number, x2: number, y2: number): string => `M${x1} ${y1} L${x2} ${y2}`;
  const paths = [seg(HC.x, HC.y - 7, 50, 13), seg(HC.x - 10, HC.y, 18, 44), seg(HC.x + 10, HC.y, 82, 44), seg(HC.x, HC.y + 7, 50, 63), seg(50, 71, 50, 86)];
  return (
    <figure class="hc" data-map="" aria-labelledby="hc-cap">
      <div class="hc__stage" data-parallax="">
        <div class="hc__atmos" aria-hidden="true"></div>
        <svg class="hc__svg" viewBox="0 0 100 100" aria-hidden="true" focusable="false">
          <circle class="hc__halo" cx={String(HC.x)} cy={String(HC.y)} r="21" />
          <circle class="hc__halo hc__halo--2" cx={String(HC.x)} cy={String(HC.y)} r="31" />
          {paths.map((d, i) => (
            <g class={`hc__link hc__link--${hcNodes[i]?.key ?? i} tone--${hcNodes[i]?.tone ?? "cyan"}`}>
              <path class="hc__path" d={d} />
              <path class={`hc__comet hc__comet--i${i}`} d={d} />
            </g>
          ))}
        </svg>
        <div class="hc__core">
          <span class="mono">Core</span>
          <strong>KrisLynx</strong>
        </div>
        {hcNodes.map((n) => (
          <a href={n.href} class={`hc__node hc__node--${n.key} tone--${n.tone}`} data-node={n.key} aria-describedby={`hc-note-${n.key}`}>
            <i aria-hidden="true"></i>
            {n.label}
          </a>
        ))}
        <div class="hc__frag hc__frag--a" aria-hidden="true">
          <p class="mono">EduLynx ERP · live product</p>
          <p class="hc__frag-big">12 modules</p>
          <p class="hc__frag-sub">4 roles · one institution record</p>
        </div>
        <div class="hc__frag hc__frag--b" aria-hidden="true">
          <p class="mono">AI layer · illustrative</p>
          <p class="hc__frag-sub">Answers only from data the user may see</p>
          <span class="hc__frag-pill">Human decision</span>
        </div>
      </div>
      <ul class="hc__notes" aria-label="What each part does">
        <li class="hc__note hc__note--default">Select a node to explore that part of the system</li>
        {hcNodes.map((n) => (
          <li class={`hc__note hc__note--${n.key}`} id={`hc-note-${n.key}`}>
            <b>{n.label}.</b> {n.note}
          </li>
        ))}
      </ul>
      <figcaption id="hc-cap" class="visually-hidden">
        The KrisLynx core connects AI, data, products, applications and the people who use them. EduLynx ERP, our live product, has twelve modules and four user roles.
      </figcaption>
    </figure>
  );
}

/* ======================================================= v3: EDULYNX ORBIT */

const orbitKeys = ["students", "attendance", "academics", "exams", "timetable", "communication", "finance", "reports", "staff", "admin", "security", "ai"] as const;

/**
 * Module relations are DERIVED from the published module descriptions, never hand-picked: module A relates to B
 * when A's description names B's core concept (and vice versa). Rule tested in tests/design.test.ts.
 */
export const moduleConcepts: Record<string, RegExp> = {
  students: /\bstudent/i, attendance: /attendance/i, academics: /academic|\bclass(es)?\b|subject|\bsections?\b/i, exams: /\bexam|marks|report card/i,
  finance: /\bfee|financ|invoice/i, communication: /notification|messag|remind/i, timetable: /timetable|period/i, reports: /\breports?\b|dashboard/i,
  staff: /\bstaff|\busers?\b|\broles?\b|teacher/i, admin: /institution|notice|calendar/i, ai: /briefing|insight/i, security: /authenticat|permission|audit/i,
};
export function relatedModules(): Record<string, string[]> {
  const rel: Record<string, Set<string>> = {};
  for (const m of edulynx.modules) rel[m.key] = new Set();
  for (const a of edulynx.modules)
    for (const [b, rx] of Object.entries(moduleConcepts))
      if (a.key !== b && rx.test(a.body) && rel[b]) { rel[a.key]?.add(b); rel[b]?.add(a.key); }
  return Object.fromEntries(Object.entries(rel).map(([k, v]) => [k, [...v].sort()]));
}
export const orbitPos = orbitKeys.map((key, i) => {
  const a = ((-90 + (360 / orbitKeys.length) * i) * Math.PI) / 180;
  return { key, x: Math.round((50 + 40 * Math.cos(a)) * 10) / 10, y: Math.round((50 + 40 * Math.sin(a)) * 10) / 10 };
});

export function EduLynxOrbit(): SafeHtml {
  const mods = orbitKeys.map((k) => edulynx.modules.find((m) => m.key === k)).filter((m) => m !== undefined);
  return (
    <div class="orb viz" data-viz="orbit" data-active="students">
      <div class="orb__grid">
        <div class="orb__stage" role="tablist" aria-label="EduLynx ERP modules">
          <svg class="orb__svg" viewBox="0 0 100 100" aria-hidden="true" focusable="false">
            <circle class="orb__ring" cx="50" cy="50" r="40" />
            <circle class="orb__ring orb__ring--inner" cx="50" cy="50" r="24" />
            {orbitPos.map((p) => (
              <line class={`orb__spoke orb__spoke--${p.key}`} x1="50" y1="50" x2={String(p.x)} y2={String(p.y)} />
            ))}
          </svg>
          <div class="orb__core" aria-hidden="true">
            <span class="mono">School operating system</span>
            <strong>EduLynx</strong>
          </div>
          {mods.map((m, i) => (
            <button type="button" role="tab" class={`orb__node orb__node--${m.key} orb__node--i${i}${m.key === "ai" ? " orb__node--ai" : ""}`} id={`orb-tab-${m.key}`} data-key={m.key} aria-controls={`orb-panel-${m.key}`} aria-selected={i === 0 ? "true" : "false"} tabindex={i === 0 ? "0" : "-1"}>
              {m.name}
            </button>
          ))}
        </div>
        <div class="orb__panels">
          {mods.map((m, i) => (
            <section class="orb__panel viz-panel" id={`orb-panel-${m.key}`} role="tabpanel" aria-labelledby={`orb-tab-${m.key}`} data-viz-panel={m.key} data-inactive={i === 0 ? undefined : ""}>
              <p class="tlabel">
                <span class="tlabel__index" aria-hidden="true">
                  {pad(i + 1)}/{pad(mods.length)}
                </span>
                <span>{m.key === "ai" ? "Intelligence layer" : m.key === "security" ? "Foundation" : "Module"}</span>
              </p>
              <h3 class="display-3">{m.name}</h3>
              <p>{m.body}</p>
              {(() => {
                const rel = relatedModules()[m.key] ?? [];
                return rel.length ? (
                  <div class="orb__rel">
                    <p class="mono">Relationships</p>
                    <ul class="orb__rel-list">
                      {rel.map((k) => (
                        <li>
                          <a href={`#orb-tab-${k}`} data-select={`orb-tab-${k}`}>
                            {edulynx.modules.find((x) => x.key === k)?.name ?? k}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : null;
              })()}
              {(() => {
                const rel = relatedModules()[m.key] ?? [];
                const names = rel.map((k) => edulynx.modules.find((x) => x.key === k)?.name ?? k);
                return rel.length ? (
                  <p class="orb__wf">
                    <span class="mono">Workflow</span> {m.name} → institution record → {names.slice(0, 3).join(" · ")}
                  </p>
                ) : null;
              })()}
              {m.key !== "security" ? (
                <a class="orb__see text-link" href={`#em-tab-${m.key}`} data-select={`em-tab-${m.key}`}>
                  See the interface →
                </a>
              ) : null}
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ===================================================== v3.1: SERVICE SYSTEMS */

/** One-line notes per step: how the work is done (method), not claims about outcomes. */
const stepNotes: Record<string, string> = {
  Idea: "Name the user and the problem in one sentence.", Architecture: "Decide the data model and how parts talk to each other.", UX: "Prototype the screens people will actually use.",
  Development: "Ship in short, reviewable increments.", QA: "Automated tests plus role-by-role checks.", Production: "Automated release to monitored infrastructure.",
  Data: "Find the records that answer the question.", Context: "Resolve who is asking and what they may see.", Models: "Choose the model that fits the task and cost.",
  Guardrails: "Validate answers against sources; refuse outside scope.", Workflow: "Put the answer where the work happens.", "Human decision": "A person reviews and decides. Always.",
  Users: "Who does the work, in which roles.", Permissions: "What each role may see and change.", Operations: "The daily workflows, modelled precisely.",
  Reports: "Reporting falls out of the data model.", Administration: "Settings, audit trail and governance.",
};

export function ServiceSystems(): SafeHtml {
  const primary = ["product-engineering", "artificial-intelligence", "enterprise-software"];
  const rest = services.filter((s) => !primary.includes(s.slug));
  return (
    <div class="ssy">
      <ol class="ssy__list">
        {primary.map((slug, i) => {
          const s = services.find((x) => x.slug === slug);
          const f = serviceFlows[slug];
          if (!s || !f) return null;
          const id = `ssy-${i}`;
          return (
            <li class="ssy__row">
              <span class="ssy__n mono">{pad(i + 1)}</span>
              <div class="ssy__head">
                <h3 class="ssy__name">{s.name}</h3>
                <p class="ssy__short">{s.short}</p>
                <a class="text-link" href={`/services/${s.slug}`}>
                  How we engineer it →
                </a>
              </div>
              <div class="ssy__sys viz" data-viz={`svc-${i}`} data-active={`${id}-0`}>
                <div class="ssy__flow" role="tablist" aria-label={`${s.name} steps`}>
                  {f.steps.map((st, j) => (
                    <button type="button" role="tab" class={`ssy__step ssy__step--i${j}`} id={`${id}-tab-${j}`} data-key={`${id}-${j}`} aria-controls={`${id}-p-${j}`} aria-selected={j === 0 ? "true" : "false"} tabindex={j === 0 ? "0" : "-1"}>
                      <span class="mono" aria-hidden="true">
                        {pad(j + 1)}
                      </span>
                      {st}
                    </button>
                  ))}
                </div>
                {f.steps.map((st, j) => (
                  <p class="ssy__note viz-panel" id={`${id}-p-${j}`} role="tabpanel" aria-labelledby={`${id}-tab-${j}`} data-viz-panel={`${id}-${j}`} data-inactive={j === 0 ? undefined : ""}>
                    <span class="mono">{pad(j + 1)} · {st}</span> {stepNotes[st] ?? ""}
                  </p>
                ))}
              </div>
            </li>
          );
        })}
      </ol>
      <p class="ssy__more">
        <span class="mono">Also</span>
        {rest.map((s) => (
          <a href={`/services/${s.slug}`}>{s.name}</a>
        ))}
      </p>
    </div>
  );
}

/* ================================================== v3.1: TECH ARCHITECTURE */

/** Layer placement for each APPROVED technology item (technology.ts). A test asserts every item is placed once. */
export const archLayers = [
  { key: "interface", name: "Interface", note: "What people touch", from: ["frontend"], role: "Screens, forms and interactions — accessible and fast on real devices.", purpose: "Make the correct action the obvious one.", path: ["interface", "application", "api"] },
  { key: "application", name: "Application", note: "Business logic", pick: ["Python", "Flask", "Node.js"], role: "Rules, workflows, validation and permissions.", purpose: "Keep the rules in one place, and tested.", path: ["interface", "application", "api"] },
  { key: "api", name: "API", note: "How parts talk", pick: ["REST APIs"], role: "Stable, authenticated contracts between the parts of a system.", purpose: "Let each part change without breaking the others.", path: ["application", "api", "services"] },
  { key: "services", name: "Services", note: "Jobs and intelligence", pick: ["Background workers"], from: ["ai"], role: "Background jobs and AI: reports, reminders, assistants.", purpose: "Do slow or smart work away from the user's request.", path: ["api", "services", "data"] },
  { key: "data", name: "Data", note: "The organization's memory", from: ["data"], role: "One data model, audited writes, reporting.", purpose: "Every module reads the same truth.", path: ["services", "data", "infrastructure"] },
  { key: "infrastructure", name: "Infrastructure", note: "Where it runs", from: ["cloud"], role: "Hosting, delivery, automated releases and monitoring.", purpose: "Releases that are repeatable and uneventful.", path: ["data", "infrastructure"] },
] as const;
export function archItems(layer: (typeof archLayers)[number]): string[] {
  const fromLayers = "from" in layer && layer.from ? layer.from.flatMap((k) => techLayers.find((l) => l.key === k)?.items ?? []) : [];
  const picked = "pick" in layer && layer.pick ? layer.pick.filter((t) => techLayers.some((l) => (l.items as readonly string[]).includes(t))) : [];
  return [...picked, ...fromLayers];
}

/**
 * Six-layer architecture (V2.1). Disclosure pattern: every layer is a native button (aria-expanded) that
 * controls its own detail region, one open at a time (Interface by default). Selecting a layer propagates a
 * signal along its real dependency path; unrelated layers stay visible but quieter. Desktop: side panel.
 * Mobile: vertical accordion. No JS: every layer expanded.
 */
export function TechArchitecture(): SafeHtml {
  const sec = techLayers.find((l) => l.key === "security");
  const name = (k: string): string => archLayers.find((l) => l.key === k)?.name ?? k;
  return (
    <figure class="arch3" data-arch="" data-active="interface" aria-labelledby="arch3-cap">
      <Fig n="04" title="Reference architecture — select a layer" />
      <div class="arch3__grid">
        <div class="arch3__stack" role="group" aria-label="Architecture layers">
          <span class="arch3__signal" aria-hidden="true"></span>
          {archLayers.map((l, i) => (
            <>
              <h3 class={`arch3__h arch3__h--i${i}`}>
                <button type="button" class={`arch3__layer arch3__layer--${l.key}`} id={`arch-btn-${l.key}`} data-key={l.key} aria-expanded={i === 0 ? "true" : "false"} aria-controls={`arch-panel-${l.key}`}>
                  <span class="arch3__id mono" aria-hidden="true">
                    L{i}
                  </span>
                  <span class="arch3__name">{l.name}</span>
                  <span class="arch3__note">{l.note}</span>
                  <span class="arch3__state mono" aria-hidden="true">
                    {i === 0 ? "Selected" : ""}
                  </span>
                </button>
              </h3>
              <div class="arch3__panel" id={`arch-panel-${l.key}`} role="region" aria-labelledby={`arch-btn-${l.key}`} data-arch-panel={l.key} data-inactive={i === 0 ? undefined : ""}>
                <p class="arch3__path mono" aria-label={`Dependency path: ${l.path.map(name).join(", then ")}`}>
                  {l.path.map((k, n) => (
                    <>
                      {n ? <span aria-hidden="true"> → </span> : null}
                      <span class={k === l.key ? "is-self" : ""}>{name(k)}</span>
                    </>
                  ))}
                </p>
                <dl class="arch3__facts">
                  <div>
                    <dt>Responsibility</dt>
                    <dd>{l.role}</dd>
                  </div>
                  <div>
                    <dt>Engineering purpose</dt>
                    <dd>{l.purpose}</dd>
                  </div>
                  <div>
                    <dt>Technology we use here</dt>
                    <dd>
                      <ul class="chips">
                        {archItems(l).map((t) => (
                          <li>{t}</li>
                        ))}
                      </ul>
                    </dd>
                  </div>
                </dl>
              </div>
            </>
          ))}
        </div>
        {sec ? (
          <aside class="arch3__rail" aria-label="Security across every layer">
            <span class="mono">Security · every layer</span>
            <ul>
              {sec.items.map((t) => (
                <li>{t}</li>
              ))}
            </ul>
          </aside>
        ) : null}
      </div>
      <p class="arch3__trace" data-arch-trace inert>
        <button type="button" class="arch3__trace-btn" data-dir="down">
          Trace a request ↓ <span class="visually-hidden">from Interface to Infrastructure</span>
        </button>
        <button type="button" class="arch3__trace-btn" data-dir="up">
          Trace a response ↑ <span class="visually-hidden">from Infrastructure to Interface</span>
        </button>
      </p>
      <figcaption id="arch3-cap" class="viz-note">
        A reference architecture, not a specific client system. Every technology shown is one we work with; each project uses the subset it needs.
      </figcaption>
    </figure>
  );
}

/* ======================================================== v3.2: SCHOOL DAY */

const dayStops = [
  { time: "07:45", key: "attendance" }, { time: "09:00", key: "academics" }, { time: "11:00", key: "communication" },
  { time: "13:00", key: "finance" }, { time: "15:00", key: "exams" }, { time: "16:30", key: "reports" },
] as const;

/** An illustrative school day. Times are an example; every description is the module's published text. */
export function SchoolDay(): SafeHtml {
  const mods = dayStops.map((d) => ({ ...d, m: edulynx.modules.find((x) => x.key === d.key) }));
  return (
    <figure class="day viz" data-viz="day" data-active={mods[0]?.key} aria-labelledby="day-cap">
      <div class="day__list" role="tablist" aria-label="A school day in EduLynx ERP">
        {mods.map((d, i) => (
          <button type="button" role="tab" class={`day__stop day__stop--i${i}`} id={`day-tab-${d.key}`} data-key={d.key} aria-controls={`day-panel-${d.key}`} aria-selected={i === 0 ? "true" : "false"} tabindex={i === 0 ? "0" : "-1"}>
            <time class="day__time mono">{d.time}</time>
            <span class="day__name">{d.m?.name ?? d.key}</span>
          </button>
        ))}
      </div>
      <div class="day__panels">
        {mods.map((d, i) => (
          <section class="day__panel viz-panel" id={`day-panel-${d.key}`} role="tabpanel" aria-labelledby={`day-tab-${d.key}`} data-viz-panel={d.key} data-inactive={i === 0 ? undefined : ""}>
            <p class="day__panel-time mono">{d.time} · example time</p>
            <h3 class="display-3">{d.m?.name}</h3>
            <p>{`${d.time} is an example point in the school day where ${d.m?.name ?? d.key} work happens — on the same institution record every other stop uses.`}</p>
            <ul class="chips">
              {featuresOf(d.m?.body ?? "").slice(0, 4).map((f) => (
                <li>{f}</li>
              ))}
            </ul>
          </section>
        ))}
      </div>
      <p class="day__record">
        <span class="mono">One record</span> Every step writes to and reads from the same institution record.
      </p>
      <figcaption id="day-cap" class="viz-note">
        Illustrative school day — the times are examples; each step shows capabilities from the module’s published description.
      </figcaption>
    </figure>
  );
}

/* ====================================================== v3.1: EDULYNX STORY */

export function EduLynxStory(): SafeHtml {
  const stops = ["School", "Students", "Academics", "Attendance", "Exams", "Finance", "Communication", "Reporting", "Administration"];
  return (
    <figure class="story" aria-labelledby="story-cap">
      <ol class="story__track">
        {stops.map((s, i) => (
          <li class={`story__stop story__stop--i${i}`}>
            <span class="mono" aria-hidden="true">
              {pad(i + 1)}
            </span>
            {s}
          </li>
        ))}
      </ol>
      <div class="story__record">
        <span class="mono">One institution record</span>
        <span>every step above reads and writes the same data</span>
      </div>
      <figcaption id="story-cap" class="visually-hidden">
        A school day in EduLynx ERP: students, academics, attendance, exams, finance, communication, reporting and administration, all on one institution record.
      </figcaption>
    </figure>
  );
}

/* ======================================================= v3: INTAKE CHIPS */

export function IntakeChips(): SafeHtml {
  const kinds = [
    { need: "new-product", label: "Product" },
    { need: "ai", label: "AI system" },
    { need: "enterprise", label: "Enterprise platform" },
    { need: "saas", label: "SaaS platform" },
    { need: "edulynx-demo", label: "EduLynx for my school" },
    { need: "other", label: "Something else" },
  ];
  return (
    <nav class="intake" aria-label="Start a project by type">
      <p class="mono intake__q">What are we building?</p>
      <ul class="intake__chips">
        {kinds.map((k) => (
          <li>
            <a href={`/contact?need=${k.need}`} data-event="cta_click" data-event-label={`intake_${k.need}`}>
              {k.label}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
}

export function vizCssV3(): string {
  const r: string[] = [];
  // interactive service diagrams: steps up to the selected one are lit
  ["product-engineering", "artificial-intelligence", "enterprise-software"].forEach((slug, i) => {
    const n = serviceFlows[slug]?.steps.length ?? 0;
    for (let j = 0; j < n; j++) r.push(Array.from({ length: j + 1 }, (_, k) => `.ssy__sys[data-active="ssy-${i}-${j}"] .ssy__step--i${k}`).join(",") + "{--lit:1}");
  });
  for (const n of hcNodes) r.push(`.hc__node--${n.key}{left:${n.x}%;top:${n.y}%}`);
  for (const p of orbitPos) r.push(`.orb__node--${p.key}{left:${p.x}%;top:${p.y}%}`);
  const rel = relatedModules();
  for (const k of orbitKeys) {
    const near = rel[k] ?? [];
    if (near.length) {
      r.push(near.map((j) => `.orb[data-active="${k}"] .orb__node--${j}`).join(",") + "{border-color:var(--orb-near);color:var(--text);background:#f3fcf7}");
      r.push(near.map((j) => `.orb[data-active="${k}"] .orb__spoke--${j}`).join(",") + "{stroke:var(--orb-near);stroke-opacity:1;stroke-width:.6}");
    }
    r.push(`.orb[data-active="${k}"] .orb__spoke--${k}{stroke:var(--orb-hot);stroke-opacity:1;stroke-width:1.1}`);
  }
  for (const n of hcNodes) r.push(`.hc[data-active="${n.key}"] .hc__note--${n.key}{display:block}.hc[data-active="${n.key}"] .hc__note--default{display:none}.hc[data-active="${n.key}"] .hc__link--${n.key} .hc__path{stroke-opacity:.95;stroke-width:.7}.hc[data-active="${n.key}"] .hc__node--${n.key}{border-color:var(--tone);background:rgba(18, 22, 20,.98);box-shadow:0 0 0 5px color-mix(in srgb,var(--tone) 16%,transparent)}`);
  // related paths: AI depends on data; applications carry people; products sit on data + apps
  const deps: Record<string, string[]> = { ai: ["data"], apps: ["people"], people: ["apps"], products: ["apps", "data"], data: ["ai", "products"] };
  for (const [k, ds] of Object.entries(deps)) r.push(ds.map((d) => `.hc[data-active="${k}"] .hc__link--${d} .hc__path`).join(",") + "{stroke-opacity:.7;stroke-width:.5}");
  r.push(`.hc[data-active="products"] .hc__frag--a{border-color:rgba(168,245,208,.55);box-shadow:0 0 0 1px rgba(168,245,208,.25),0 24px 50px -24px rgba(0,0,0,.8)}`);
  r.push(`.hc[data-active="ai"] .hc__frag--b{border-color:rgba(200,184,255,.6)}`);
  r.push(`.hc[data-active="people"] .hc__atmos{opacity:1}`);
  // V2.1 architecture: grid rows, dependency propagation, signal travel (desktop)
  const idx = (k: string): number => archLayers.findIndex((l) => l.key === k);
  // desktop only: layers occupy rows 1–6 beside the detail column; on mobile DOM order makes each panel open under its layer
  r.push("@media (min-width:64rem){" + archLayers.map((_l, i) => `.js .arch3__h--i${i}{grid-row:${i + 1}}`).join("") + "}");
  r.push("@media (scripting:enabled) and (min-width:64rem){" + archLayers.map((_l, i) => `.arch3__h--i${i}{grid-row:${i + 1}}`).join("") + "}");
  for (const l of archLayers) {
    l.path.forEach((k, n) => r.push(`.arch3[data-active="${l.key}"] .arch3__layer--${k}{--on:1;transition-delay:${n * 110}ms}`));
    const a = idx(l.path[0] ?? l.key), b = idx(l.path[l.path.length - 1] ?? l.key);
    r.push(`@keyframes arch-sig-${l.key}{0%{top:calc(${a} * var(--arch-step) + var(--arch-mid));opacity:0}12%{opacity:1}88%{opacity:1}100%{top:calc(${b} * var(--arch-step) + var(--arch-mid));opacity:0}}`);
    r.push(`@media (prefers-reduced-motion: no-preference){.arch3[data-active="${l.key}"] .arch3__signal{animation:arch-sig-${l.key} ${260 + (b - a) * 180}ms var(--ease-out-kx) both}}`);
  }
  return r.join("\n") + "\n";
}
