/**
 * Generates docs/reports/SEO-AUDIT.md and docs/reports/PERFORMANCE-AUDIT.md from
 * the built site. Run after `npm run build`. Numbers are measured, not estimated.
 */
import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { join } from "node:path";

const DIST = "dist";
const htmlFiles = (dir: string): string[] =>
  readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? htmlFiles(p) : p.endsWith(".html") ? [p] : [];
  });
const kb = (n: number): string => `${(n / 1024).toFixed(1)} KB`;
const gz = (buf: Buffer | string): number => gzipSync(buf, { level: 9 }).length;

const rows: string[] = [];
const perf: string[] = [];
const files = htmlFiles(DIST).sort();
const css = readdirSync(join(DIST, "assets")).find((f) => f.endsWith(".css")) ?? "";
const js = readdirSync(join(DIST, "assets")).find((f) => f.endsWith(".js")) ?? "";
const cssBuf = readFileSync(join(DIST, "assets", css));
const jsBuf = readFileSync(join(DIST, "assets", js));

for (const f of files) {
  const html = readFileSync(f, "utf8");
  const route = "/" + f.replace(/^dist\//, "").replace(/\.html$/, "").replace(/^index$/, "");
  const title = /<title>([^<]*)/.exec(html)?.[1]?.replace(/&amp;/g, "&") ?? "";
  const desc = /<meta name="description" content="([^"]*)/.exec(html)?.[1] ?? "";
  const robots = /<meta name="robots" content="([^"]*)/.exec(html)?.[1] ?? "";
  const canonical = /<link rel="canonical" href="([^"]*)/.exec(html)?.[1] ?? "—";
  const h1 = (html.match(/<h1[\s>]/g) ?? []).length;
  const types = [...html.matchAll(/"@type":"(\w+)"/g)].map((m) => m[1]);
  const topTypes = [...new Set(types.filter((t) => ["Organization", "WebSite", "WebPage", "AboutPage", "ContactPage", "CollectionPage", "Service", "SoftwareApplication", "Article", "BreadcrumbList", "JobPosting"].includes(t ?? "")))];
  const internal = new Set([...html.matchAll(/href="(\/[^"#?]*)/g)].map((m) => m[1])).size;
  rows.push(
    `| \`${route}\` | ${robots.startsWith("noindex") ? "noindex" : "index"} | ${title.length} | ${desc.length} | ${h1} | ${canonical === "—" ? "—" : "✓"} | ${topTypes.join(", ") || "—"} | ${internal} |`,
  );
  const imgs = [...html.matchAll(/<img\b[^>]*>/g)].map((m) => m[0]).filter((t) => t.includes('loading="eager"')).map((t) => /\ssrc="([^"]+)"/.exec(t)?.[1] ?? "");
  const lcp = imgs[0] && existsSync(join(DIST, imgs[0])) ? statSync(join(DIST, imgs[0])).size : 0;
  const lazyImgs = (html.match(/loading="lazy"/g) ?? []).length;
  perf.push(`| \`${route}\` | ${kb(gz(html))} | ${kb(gz(html) + gz(cssBuf) + gz(jsBuf))} | ${lcp ? kb(lcp) + " (jpg fallback)" : "text (no image)"} | ${lazyImgs} |`);
}

mkdirSync("docs/reports", { recursive: true });
const date = new Date().toISOString().slice(0, 10);
writeFileSync(
  "docs/reports/SEO-AUDIT.md",
  `# SEO audit — generated ${date}

Generated by \`npm run audit:site\` from \`dist/\`. Title/description columns are character counts
(targets: title ≤ 60 before the " | KrisLynx" suffix is not appended to absolute titles; description 70–160).

| Route | Indexing | Title chars | Desc chars | h1 | Canonical | Structured data | Internal links |
|---|---|---|---|---|---|---|---|
${rows.join("\n")}

## Site-wide
- \`robots.txt\`: allows all, disallows \`/api/\` and \`/contact/thanks\`, references the sitemap.
- \`sitemap.xml\`: ${(readFileSync(join(DIST, "sitemap.xml"), "utf8").match(/<loc>/g) ?? []).length} URLs, all indexable and all resolving (verified by \`tests/site.test.ts\`).
- Every page has Open Graph + Twitter card tags and a dedicated 1200×630 image.
- Legacy URLs 301-redirect (see \`firebase.json\`), preserving any existing link equity.
`,
);
writeFileSync(
  "docs/reports/PERFORMANCE-AUDIT.md",
  `# Performance audit — generated ${date}

Measured from the production build. Lighthouse could not be run in the offline build environment;
run it against the deployed site (see docs/QA-REPORT.md, "Checks to run after deploy").

## Shared assets (every page)
| Asset | Raw | Gzip |
|---|---|---|
| CSS \`${css}\` | ${kb(cssBuf.length)} | ${kb(gz(cssBuf))} |
| JS \`${js}\` | ${kb(jsBuf.length)} | ${kb(gz(jsBuf))} |

The JS is deferred and only enhances the page (menu, tabs, assistant, form); all content renders without it.
Hashed filenames are served with \`Cache-Control: immutable, max-age=1y\`.

## Per page (first visit, excluding web fonts)
| Route | HTML gzip | HTML+CSS+JS gzip | Priority image | Lazy images |
|---|---|---|---|---|
${perf.join("\n")}

Images are served as AVIF → WebP → JPEG via \`<picture>\` with responsive \`srcset\`; browsers that support AVIF
download far less than the JPEG size listed. Every \`<img>\` declares width/height (no layout shift).

## Web fonts
Self-hosted (public/fonts): Bricolage Grotesque 700, Instrument Sans 400/700, Geist Mono 400 — WOFF2, subset, 61 KB total, font-display swap, two critical faces preloaded. No third-party font requests.
`,
);
console.log(`✓ audit reports for ${files.length} pages → docs/reports/`);
